### ISSUE TITLE
how to solve it or it's a bug?

### ISSUE THREAD

**Issue by zhuyu4839** [laborer/stcflash#8]
Traceback (most recent call last):
  File "stcflash.py", line 637, in <module>
    main()
  File "stcflash.py", line 610, in main
    aispbaud = int(a)
ValueError: invalid literal for int() with base 10: './test.bin'

**Comment by laborer** [comment]
Please paste the full command you used with arguments.  It looks like that you didn't specify an integer after argument --aispbaud to set the baud rate for auto ISP.
