### ISSUE TITLE
Read flash

### ISSUE THREAD

**Issue by AlexDaniel** [laborer/stcflash#9]
Hi!
It seems like currently there is no way to read flash from the device (this feature is not available even in their own tool).

However, I really need this feature for one of the projects I'm working on.

Perhaps there is a way to implement it? E.g. maybe the verify sequence can be abused to get the data?

**Comment by laborer** [comment]
I don't think that there exists a non-intrusive method for reading the code.

Here is a [related discussion](https://github.com/grigorig/stcgal/issues/7).
